#standardSQL
SELECT
  CONCAT('20', SUBSTR(_TABLE_SUFFIX, 0, 8)) AS date,
  UNIX_DATE(CAST(REPLACE(CONCAT('20', SUBSTR(_TABLE_SUFFIX, 0, 8)), '_', '-') AS DATE)) * 1000 * 60 * 60 * 24 AS timestamp,
  IF(STRPOS(_TABLE_SUFFIX, '_mobile') = 0, 'desktop', 'mobile') AS client,
  ROUND(APPROX_QUANTILES(reqJS, 1000)[OFFSET(100)], 2) AS p10,
  ROUND(APPROX_QUANTILES(reqJS, 1000)[OFFSET(250)], 2) AS p25,
  ROUND(APPROX_QUANTILES(reqJS, 1000)[OFFSET(500)], 2) AS p50,
  ROUND(APPROX_QUANTILES(reqJS, 1000)[OFFSET(750)], 2) AS p75,
  ROUND(APPROX_QUANTILES(reqJS, 1000)[OFFSET(900)], 2) AS p90
FROM
  `httparchive.runs.20*`
WHERE
  _TABLE_SUFFIX LIKE '%_pages%'
GROUP BY
  date,
  timestamp,
  client
ORDER BY
  date DESC,
  client
