csp = {
    "default-src": "'self'",
    "style-src": ["'self'", "'unsafe-inline'"],
    "script-src": [
        "'self'",
        "'strict-dynamic'",
        "cdn.httparchive.org",
        "*.googletagmanager.com",
        "cdn.speedcurve.com",
        "spdcrv.global.ssl.fastly.net",
        "lux.speedcurve.com",
        "'unsafe-inline'",
        "reports-dev-2vzgiib6.uc.gateway.dev",
        "reports-prod-2vzgiib6.uc.gateway.dev",
    ],
    "font-src": ["'self'"],
    "connect-src": [
        "'self'",
        "cdn.httparchive.org",
        "discuss.httparchive.org",
        "dev.to",
        "cdn.rawgit.com",
        "export.highcharts.com",
        "www.webpagetest.org",
        "*.analytics.google.com",
        "*.google-analytics.com",
        "*.googletagmanager.com",
        "*.speedcurve.com",
        "reports-dev-2vzgiib6.uc.gateway.dev",
        "reports-prod-2vzgiib6.uc.gateway.dev",
    ],
    "img-src": [
        "'self'",
        "https:",
        "*.google-analytics.com",
        "*.googletagmanager.com",
    ],
    "frame-src": ["'none'"],
    "object-src": ["'none'"],
    "base-uri": ["'none'"],
}
