######################################
## Custom HTTP Archive GitHub action ##
######################################
#
# A pre-deploy script that must be run in GitHub Actions to:
# - Generate the scripts
# - Update timestamps and hashes
# - Submit a Pull Request with the changes (if any)
#
# This should be run before every release
#
name: Predeploy script

on:
  workflow_dispatch:

jobs:
  build:
    name: Generate Scripts and Update Timestamps
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2.4.0
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v2.5.1
      with:
        node-version: '15'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.8'
    - name: Run the website
      run: ./tools/scripts/run_and_test_website.sh
    - name: Update timestamps
      run: npm run timestamps
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3.12.0
      with:
        title: Pre-deploy Updates
        branch-suffix: timestamp
        commit-message: Generate Scripts and Update Timestamps
        body: |
          Generate Scripts and Update Timestamps through GitHub action
          - Auto-generated by [create-pull-request][1] GitHub Action

          [1]: https://github.com/peter-evans/create-pull-request
    - name: Check outputs
      run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
